server:
  port: 0

spring:
  application:
    name: spring-cloud-project-test

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.javaninja: INFO

